const SITE_CONTENT = {
  logo: 'images/logo.jpg',
  phone: '+7 (981) 008 36 40',
  navLinks: [
    { label: 'Футболки', filter: 'tshirt' },
    { label: 'Худи', filter: 'hoodie' },
    { label: 'Для медиков', filter: 'medical' },
    { label: 'Для ветеринаров', filter: 'vet' }
  ],
  banner: { show: true, text: 'Бесплатная доставка при заказе от 5 000 ₽' },
  catalogTitle: 'Стильные принты для врачей: медикам и ветеринарам',
  catalogSubtitle: 'Футболки и худи с авторскими принтами',
  products: [
    {
      name: 'Футболка «Рука Бога»',
      price: 2900,
      oldPrice: null,
      type: 'tshirt',
      tags: ['medical'],
      colors: ['#ffffff', '#1a1a1a'],
      sizes: 'XS — XXL',
      badge: null,
      image: 'images/t-creation.jpg',
    },
    {
      name: 'Футболка «Спрей от проблем»',
      price: 2900,
      oldPrice: null,
      type: 'tshirt',
      tags: ['medical'],
      colors: ['#ffffff', '#1a1a1a', '#1652a0'],
      sizes: 'XS — XXL',
      badge: null,
      image: null,
    },
    {
      name: 'Худи «Анестезиолог»',
      price: 4900,
      oldPrice: null,
      type: 'hoodie',
      tags: ['medical'],
      colors: ['#f0a890', '#1a1a1a', '#ffffff'],
      sizes: 'S — XXL',
      badge: 'NEW',
      image: 'images/hoodie-creation.jpg',
    },
    {
      name: 'Футболка «Сердце»',
      price: 2900,
      oldPrice: 3400,
      type: 'tshirt',
      tags: ['medical'],
      colors: ['#ffffff', '#1a1a1a'],
      sizes: 'XS — XXL',
      badge: 'SALE',
      image: null,
    },
    {
      name: 'Худи «Франкен Врач»',
      price: 4900,
      oldPrice: null,
      type: 'hoodie',
      tags: ['vet'],
      colors: ['#e8ddd3', '#1a1a1a'],
      sizes: 'S — XXL',
      badge: null,
      image: null,
    },
    {
      name: 'Футболка «Врач и Искусство»',
      price: 2900,
      oldPrice: null,
      type: 'tshirt',
      tags: ['medical'],
      colors: ['#ffffff', '#1a1a1a'],
      sizes: 'XS — XXL',
      badge: null,
      image: null,
    }
  ],
  advantages: [
    { icon: 'truck', title: 'Бесплатная доставка', text: 'от 5 000 ₽' },
    { icon: 'shield', title: 'Гарантия возврата', text: '14 дней' },
    { icon: 'star', title: '100% хлопок', text: 'премиум качество' },
    { icon: 'clock', title: 'Быстрая отправка', text: '1–2 рабочих дня' }
  ],
  seoTitle: 'Одежда с принтами для врачей: медиков и ветеринаров',
  seoText: 'Интернет-магазин НеХалат предлагает стильные футболки и худи с авторскими принтами для врачей, хирургов и ветеринаров. Мы используем 100% хлопок для футболок и качественную смесовую ткань для худи (80% хлопок, 20% полиэстер). Стойкая печать не выцветает после стирки. Доставка по всей России службами СДЭК и Почтой России.',
  footerAbout: 'Стильная одежда с принтами для тех, кто гордится своей профессией.',
  contactEmail: 'nehalat@yandex.ru',
  contactPhone: '+7 (981) 008 36 40',
  instagramUrl: '',
  whatsappUrl: '',
  copyright: '© 2026 НеХалат. Все права защищены.',
};
